# VCNetworkKit-Session document generator jazzy settings

copyright: Copyright 2020 Vicente Crespo
author: Vicente Crespo
xcodebuild_arguments: [-target, VCNetworkKit-Session-iOS]
clean: true
output: ./Documentation
